### ISSUE TITLE
How can I use this task on a build?

### ISSUE THREAD

**Issue by dengyakui** [sevaa/tfvcget#3]
I have a common project to store some common scripts, and I need to fetch the  files when build another project ,but now I can't find the task in  build tasks, hope to use the task in build phase.

**Comment by sevaa** [comment]
You don't need this task in the build phase, because build definitions (AKA pipelines) have a built-in "get files from source control" task in the beginning. You can add more than one source control folder to it if you wish, and they may come from another project.

![image](https://user-images.githubusercontent.com/5807738/57777803-b7d61500-76f0-11e9-90b1-2b37bcd98708.png)

**Comment by dengyakui** [comment]
Thanks for reply.  When my project is based tfvc, it's ok to use workspace map to fetch other tfvc files.But if the project uses git repo, I can only fetch one source code, so I want to use your extension to fetch another tfvc repo's file during the build.

**Comment by sevaa** [comment]
Good point. Updated, published, it will show up for build definitions, too. Please check.

**Comment by dengyakui** [comment]
666 thanks!
